
# training
iterations = 100000
batch_size = 64
num_workers = 10

# gunpowder nodes
noise_max = 0.1
lsd_sigma = 20
snapshot_dir = '/nrs/funke/data/mhat/synthetic_data/snapshots_folder/run3'

# data
input_dir = "/nrs/funke/data/mother_machine/synthetic_data/dataset1/"
input_zarr_glob = "*.zarr"
input_shape = [3, 400, 36]
input_voxel_size = [1, 1, 1]
