drift = 5
drift_weight = 1.0
drift_constant = -10.0
area_weight = 0.5
area_constant = 0
cohesion_weight = -10
cohesion_constant = 10
adhesion_weight = -100
adhesion_constant = 0
appear_constant = 200.0
disappear_constant = 200.0

min_merge_score = 0.0
max_merge_score = 0.5
max_edge_distance = 30

size_threshold = 50
