# IO
input_base_dir = "/Volumes/funke/data/mother_machine/synthetic_data/"
output_base_dir = "/Volumes/funke/projects/darts/experiments/results/"
dataset = "validation1"
exp_name = "2024-08-15_12-05-16"

# Eval settings
iou_threshold = 0.25
